[package]
name = "uma-db"
version = "0.1.0"
edition = "2024"

[dependencies]
uma-core = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
dotenvy = { workspace = true }
thiserror = { workspace = true }
sqlx = { workspace = true }